export {default as Loader} from './mini/Loader'
export {default as NavBar} from './nav/NavBar'
export {default as Transactions} from './crypto/Transactions'
export {default as WelcomeWallet} from './crypto/WelcomeWallet'
export {default as Services} from './portfolio/Services'
//export {default as Footer} from './Footer' 
