import React from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import FbHeader from '../components/fbcomponents/FbHeader'
import Link from 'next/link'
import { getSession } from 'next-auth/react'
import { Session } from 'next-auth'
import Login from '../components/fbcomponents/Login'
import SideBar from '../components/fbcomponents/SideBar'
import BakeryItems from '../components/fbcomponents/BakeryItems'
import Stories from '../components/fbcomponents/Stories'
//destructured our prop, without the curly braces




const Facebook: any = (session: Session) => {
  

  
    if(!session){
        return <Login/>
    }
  
  /*  if(session.expires=="")
        return <Refresh/>*/

return (
    <div className='h-screen bg-gray-50'> <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <h2>
      <Link href="/">Back to home</Link>
    </h2>
    <h2>
    </h2>
  {/**lets buikd our header */}
    <FbHeader/>
  {/**and our main, rest of our page */}
    <main>
      <div className='flex'>
            <SideBar />
            <div className='firstSection
      '> 
              <BakeryItems />
              <Stories stories={[]} />
            </div>
          
            
      </div>

    {/*SideBar*/}
    {/*Feed*/}
    {/*Widget*/}
</main>
</div>
)
}
export const getServerSideProps:GetServerSideProps=async(context)=>{
  //get user , are you logged in or not?
  const session=await getSession(context);
  return {
    props:{
      session
    }
  }
}
export default Facebook